// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf8hXTJqpiNtaq45kGMxMkwUmRnlTdTCM',
    appId: '1:283700309050:web:de2d13c5f77ce5def2d903',
    messagingSenderId: '283700309050',
    projectId: 'pushnotification-86d31',
    authDomain: 'pushnotification-86d31.firebaseapp.com',
    storageBucket: 'pushnotification-86d31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTp3z8T0imSp6ZeFzYq1aM2b0izK2M_gQ',
    appId: '1:283700309050:android:0f4bffff406e4c6bf2d903',
    messagingSenderId: '283700309050',
    projectId: 'pushnotification-86d31',
    storageBucket: 'pushnotification-86d31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDegoTXV-aPZhnt88KYPIM_zAjWyJbkKPY',
    appId: '1:283700309050:ios:88b31eac732c4198f2d903',
    messagingSenderId: '283700309050',
    projectId: 'pushnotification-86d31',
    storageBucket: 'pushnotification-86d31.firebasestorage.app',
    iosBundleId: 'com.example.tresTristesTigres',
  );
}
